In [1]:
import numpy as np
a=np.array([3,4,5,6,7,9])
print(a)

[3 4 5 6 7 9]


In [2]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(np.zeros((3,3)))


[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [9]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Dimension of Matrix:",np.shape(a))

Dimension of Matrix: (3, 3)


In [13]:
print(np.ones((3,3)))

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [14]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [18]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
a=np.arange(3,4,0.2)
print(a)

[ 3.   3.2  3.4  3.6  3.8]


In [23]:
a=np.linspace(2,4,5)
print(a)

[ 2.   2.5  3.   3.5  4. ]


In [26]:
a=np.floor(100*np.random.random((3,3)))
print(a)

[[ 64.  80.  67.]
 [ 18.  58.  19.]
 [ 79.  12.  56.]]


In [27]:
#Matrix Multiplication
a=np.arange(4).reshape((2,2))
b=np.arange(4).reshape((2,2))
c=np.dot(a,b)
print(c)

[[ 2  3]
 [ 6 11]]


In [32]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Before Transpose:")
print(a)
print("After Transpose:")
print(a.transpose())


Before Transpose:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After Transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [1]:
import numpy as np
from scipy.linalg import svd
x=np.array([[1,2,3],[4,5,6],[5,6,7]])
u,s,t=svd(x)
print("x=",x)
print("u=",u)
print("s=",s)
print("t=",t)

x= [[1 2 3]
 [4 5 6]
 [5 6 7]]
u= [[-0.25775879  0.94609665  0.19611614]
 [-0.62014124 -0.00634259 -0.78446454]
 [-0.74093539 -0.32382234  0.58834841]]
s= [  1.41499421e+01   8.82688844e-01   2.95742808e-16]
t= [[-0.4553376  -0.5697434  -0.6841492 ]
 [-0.79120225 -0.09341194  0.60437836]
 [ 0.40824829 -0.81649658  0.40824829]]
